### ISSUE TITLE
Request timeout

### ISSUE THREAD

**Issue by bittremieux** [wfondrie/ppx#11]
Provide a timeout option to kill indefinitely hanging requests.

**Comment by wfondrie** [comment]
Update: PR #13 adds timeout arguments, but currently we're running into issues with PRIDE's server. It maybe related to their ongoing infrastructure issues, that I mentioned in Issue #12. Regardless, I want to resolve these before merging anything else.

**Comment by bittremieux** [comment]
I haven't had problems with hanging requests anymore, even when performing parallel requests without a sleep. It might have been related to the recent PRIDE FTP issues? My script also runs _much_ faster now than two weeks ago. Everything seems fine now though, both interfacing with PRIDE directly and using ppx.

**Comment by wfondrie** [comment]
Cool! I'll still add it, but hopefully the option won't be too necessary.
