### ISSUE TITLE
Add cloud backend support

### ISSUE THREAD

**Issue by wfondrie** [wfondrie/ppx#24]
It would be nice to add support for storing files on AWS S3. This will take a bit of work to configure the back-end to work with boto3 instead of normal file paths. The goal would be that something like this could be done if your AWS credentials are configured:

```python
import ppx

# Specify an S3 bucket as the location of the project:
proj = ppx.find_project("PXD000001", local="s3://mybucket")

# List the raw files we want to transfer:
raw_files = proj.remote_files("*.raw")

# Move them to S3. This would be fast from an EC2 instance:
downloaded = proj.download(raw_files)

# 'downloaded' would contain the S3 URIs
```

**Comment by sooheon** [comment]
If you are busy, I am interested in contributing this feature for GCP storage.

Mechanically, are you thinking the FTP transfer to local storage happens first and then transfer from there to cloud storage? This has the downside of two hops but is much simpler than trying to stream directly from FTP to cloud (which I don't think is supported OOTB for the GCP client at least).

**Comment by sooheon** [comment]
I was less familiar w S3, it looks like streaming with retrbinary -> s3 is simple.

**Comment by sooheon** [comment]
fsspec (used by pandas dask etc.) makes FTP -> cloud/local filesystem transparent, but because your project uses pathlib, the integration wasn't clean. 

cloudpathlib is API compatible w/ pathlib and is very easy to add.
